---
openapi: 3.0.0
info:
  version: 1.0.0
  title: https://u.icq.net
servers:
- url: https://u.icq.net
tags:
- name: Авторизация
paths:
  "/rapi/auth/sendCode":
    post:
      tags:
      - Авторизация
